version: "3.7"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: mailbox
      POSTGRES_PASSWORD: mailbox
    ports:
      - 5432:5432
    volumes:
      - ./src/db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mailbox"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    image: thorstenthiel/phishy-mailbox:v1.2.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: v1.2.1
    environment:
      DATABASE_URL: postgresql://mailbox:mailbox@postgres:5432/mailbox?schema=public
      NEXTAUTH_SECRET: secret1234256w5w4
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
